"""Subclass of mainFrame, which is generated by wxFormBuilder."""

import wx
import omnibusFrame

# Implementing mainFrame
class excelFramemainFrame( omnibusFrame.mainFrame ):
    def __init__( self, parent ):
        omnibusFrame.mainFrame.__init__( self, parent )
        self.p1 = omnibusFrame.panelGrid(self)
        self.p2 = omnibusFrame.panel2(self)
        self.p2.Hide()

    # Handlers for mainFrame events.
    def OnM_switchToGrid( self, event ):
        # TODO: Implement OnM_switchToGrid
        if self.p1.IsShown():
            return
        self.p2.Hide()
        self.p1.Show()


    def OnM_switchToText( self, event ):
        # TODO: Implement OnM_switchToText
        if self.p2.IsShown():
            return
        self.p1.Hide()
        self.p2.Show()



if __name__ == '__main__':
    app = wx.App()
    excelFramemainFrame(None).Show()
    app.MainLoop()